
http://127.0.0.1:3000/api/v1/products/

###
http://127.0.0.1:3000/api/v1/products/6

###
http://127.0.0.1:3000/api/v1/workout/damien
###
POST http://127.0.0.1:3000/api/v1/workout/damien
Content-Type: application/json

{
    "reps": 3,
    "sets": 5,
    "name": "pushup"
}

###
PATCH http://127.0.0.1:3000/api/v1/workout/damien/pushup