
http://127.0.0.1:3003/api/v1/workout/1

###
http://127.0.0.1:3000/api/v1/products/6

###
http://localhost:3003/api/v1/workout/1
###
POST http://127.0.0.1:3003/api/v1/workout/1
Content-Type: application/json

{
    "name": "9",
    "reps": 443,
    "sets": 1443,
    "image": "1",
    "completed": false,
    "time": ""
}

###
PATCH http://127.0.0.1:3003/api/v1/workout/1/null/true